title: CS Workshop
description: Code Switching Workshop
details: Collocated with LREC 2020
github:
  owner_name: Jason
  wi_url: 2020/wi.html
  oc_url: 2020/oc.html
  pc_url: 2020/pc.html
dates:
  - name: Workshop date
    date: Saturday May 16th, 2020
  - name: Paper submission
    date: February 28th, 2020
  - name: Notification of acceptance
    date: March 23rd, 2020
  - name: Camera ready submission deadline
    date: April 5th, 2020
Links: https://lrec2020.lrec-conf.org/en/
Venue: Le Palais du Pharo



twitter: https://twitter.com/WCALCS
workshops:
  - year: 2018
    name: CALCS 2018
    venue: ACL (Melbourne, Autralia)
  - year: 2020
    name: CALCS 2020
    venue: COLING (Spain)
  - year: 2021
    name: CALCS 2021
    venue: TBD
  - year: 2023
    name: CALCS 2023
    venue: EMNLP (Singapore)
  - year: 2025
    name: CALCS 2025
    venue: NAACL (New Mexico, USA)