title: CS Workshop - 2020
description: Code Switching Workshop
details: Collocated with LREC 2020
github:
  owner_name: Jason
  wi_url: 2020/wi.html
  oc_url: 2020/oc.html
  pc_url: 2020/pc.html
dates:
  - name: Workshop date
    date: Saturday May 16th, 2020
  - name: Paper submission
    date: February 28th, 2020
  - name: Notification of acceptance
    date: March 23rd, 2020
  - name: Camera ready submission deadline
    date: April 5th, 2020
Links: https://lrec2020.lrec-conf.org/en/
Venue: Le Palais du Pharo
PastWorkShops:
  - name: 2018/
    link: https://code-switching.github.io/2018
  - name: 2020/
    link: https://code-switching.github.io/2020
